Initial commit for GPS direction and positioning lab
microsoft/iot-curriculum pull request #34
Opened 2020-10-20 18:54 UTC by moizhraj

This commit contains a lab with multiple parts showing GPS Direction and Positioning using an STM32L475E-IOT01A board and a Neo 6M GPS sensor using Azure IoT services and Azure Maps.

2020-11-17 17:46 UTC, jimbobbennett commented
Can you add a link to this to the README.md file in the labs folder please.

2020-11-18 20:12 UTC, jimbobbennett requested changes

2020-11-24 19:08 UTC, moizhraj commented on .gitmodules
> +[submodule "labs/iot/gps-directions-and-positioning/code/stm32/core/lib/threadx"]
Other way is to include the entire source.

If user is just doing a git clone then these submodules will not initialize and fetch.

2020-11-25 03:16 UTC, moizhraj commented on labs/iot/gps-directions-and-positioning/README.md
> +| Learning Objectives | <ul><li>Set up dev environment</li><li>Set up IoT Hub</li><li>Send data from a device to IoT Hub</li><li>Call a device function from IoT Hub/Azure IoT Explorer</li><li>Send Cl
Not really, unless we want to include a separate document to explain on how to setup RTOS? Let me know.

2020-11-25 18:00 UTC, jimbobbennett commented on labs/iot/gps-directions-and-positioning/README.md
> +| Learning Objectives | <ul><li>Set up dev environment</li><li>Set up IoT Hub</li><li>Send data from a device to IoT Hub</li><li>Call a device function from IoT Hub/Azure IoT Explorer</li><li>Send Cl
But the user has to set this up to make the sample work, so doesn't that count as a learning objective?

2021-03-15 20:34 UTC, closed without merging